#obtain an API login_id and transaction_id according to instructions at https://developer.authorize.net/faqs/#gettranskey
api_login_id: 37XCbbHD93tZ
api_transaction_key: 5a69ctT9B77P7g7Z

#obtained md5 hash value by first setting the hash value in https://sandbox.authorize.net/ under the Account tab->MD5 Hash
md5_value: MD5_TEST